name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build source
        run: |
          bash build.sh osd-goke
          bash build.sh osd-hisi
          bash build.sh osd-star6b0
          bash build.sh osd-star6e

      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            osd/osd-goke
            osd/osd-hisi
            osd/osd-star6b0
            osd/osd-star6e
